{"url": "https://towardsdatascience.com/exception-handling-in-python-7f639ce9a3d", "time": 1683007440.025686, "path": "towardsdatascience.com/exception-handling-in-python-7f639ce9a3d/", "webpage": {"metadata": {"title": "Exception Handling in Python. Introduction to Exception Handling in\u2026 | by Sadrach Pierre, Ph.D. | Towards Data Science", "h1": "Exception Handling in Python", "description": "Exception handling is the method of programmatically responding to unusual conditions that require special processing. In python, it is straight forward to implement exception handling for a wide\u2026"}, "outgoing_paragraph_urls": [{"url": "https://github.com/spierre91/medium_code/blob/master/basic_python/exception_handling.py", "anchor_text": "GitHub", "paragraph_index": 18}], "all_paragraphs": ["Exception handling is the method of programmatically responding to unusual conditions that require special processing. In python, it is straight forward to implement exception handling for a wide variety of error types. In this post, we will discuss how to implement exception handling in python.", "First, let\u2019s consider the following list of integers:", "We can iterate over the list and print the elements using a \u2018for-loop\u2019:", "Within the \u2018for-loop\u2019 we can also perform operations and print the results. Let\u2019s calculate the square of each element and print the result;", "Suppose our list also contained the string value, \u20186\u2019:", "Let\u2019s try to calculate the square of each element in this new list. This will return a \u2018TypeError\u2019:", "The error specifies the line of problematic code:", "The \u2018TypeError\u2019 was raised because the operand \u2018str\u2019 is not supported for the \u2018**\u2019 power operator. Suppose we want our code to have a way of processing string valued integers without throwing an error. This is where exception handling comes into play. We can handle the \u2018TypeError\u2019 using the python keywords try and except. First, let\u2019s try to square and print each value:", "When we get a \u2018TypeError\u2019, we use the except keyword to handle the \u2018TypeError\u2019. Since the string contains a numerical value, we can use the \u2018int()\u2019 method to convert the string into an integer and calculate the square within the exception:", "It\u2019s worth noting that the way we handle errors highly depends on the error type and the type of data we are processing.", "Next, suppose our list contains a word or another type like a list. We want to be able handle these errors without having our code fail to produce any output. Let\u2019s consider the following list which contains the string \u2018##\u2019:", "If we try to loop over this new list and calculate the square we get a \u2018ValueError\u2019:", "This error is saying that we can\u2019t convert the string, \u2018##\u2019, into an integer. We need to write extra processing for this error type. For example, we can replace the string with some filler value, like 0 or \u2018NaN\u2019:", "Let\u2019s consider another example of exception handling. Suppose we have the following list of strings containing programming languages:", "We can use the \u2018split()\u2019 method to split the strings and add the text \u2018is awesome\u2019 using the \u2018+\u2019 operator:", "Since the \u2018split()\u2019 method is a string object method, an \u2018AttributeError\u2019 will be raised if there are non-string values in our list. Let\u2019s add a dictionary to our list and run our code again:", "The error says the \u2018dict()\u2019 object has no attribute \u2018split()\u2019. Let\u2019s write some try/except logic to handle this error:", "I\u2019ll stop here but I encourage you to play around with the code yourself.", "To summarize, in this post we discussed exception handling in python. We showed how to use try/except keywords and error types to handle bad values in data. We look at examples of handling the \u2018TypeError\u2019 and the \u2018AttributeError\u2019. I encourage you to look in to the additional error types and how to handle them. Additional error types include \u2018SyntaxError\u2019, \u2018ZeroDivisionError\u2019, \u2018FileNotFoundError\u2019 and much more. I hope you found this post useful/interesting. The code in this post is available on GitHub. Thank you for reading!", "Your home for data science. A Medium publication sharing concepts, ideas and codes.", "Writer for Built In & Towards Data Science. Cornell University Ph. D. in Chemical Physics."], "all_outgoing_urls": [{"url": "https://rsci.app.link/?%24canonical_url=https%3A%2F%2Fmedium.com%2Fp%2F7f639ce9a3d&%7Efeature=LoOpenInAppButton&%7Echannel=ShowPostUnderCollection&source=---two_column_layout_nav----------------------------------", "anchor_text": "Open in app"}, {"url": "https://medium.com/m/signin?operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&source=post_page---two_column_layout_nav-----------------------global_nav-----------", "anchor_text": "Sign up"}, {"url": "https://medium.com/m/signin?operation=login&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&source=post_page---two_column_layout_nav-----------------------global_nav-----------", "anchor_text": "Sign In"}, {"url": "https://medium.com/?source=---two_column_layout_nav----------------------------------", "anchor_text": ""}, {"url": "https://medium.com/m/signin?operation=register&redirect=https%3A%2F%2Fmedium.com%2Fnew-story&source=---two_column_layout_nav-----------------------new_post_sidenav-----------", "anchor_text": "Write"}, {"url": "https://medium.com/search?source=---two_column_layout_nav----------------------------------", "anchor_text": ""}, {"url": "https://medium.com/m/signin?operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&source=post_page---two_column_layout_nav-----------------------global_nav-----------", "anchor_text": "Sign up"}, {"url": "https://medium.com/m/signin?operation=login&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&source=post_page---two_column_layout_nav-----------------------global_nav-----------", "anchor_text": "Sign In"}, {"url": "https://towardsdatascience.com/?source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": ""}, {"url": "https://towardsdatascience.com/?source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": "Towards Data Science"}, {"url": "https://spierre91.medium.com/?source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": ""}, {"url": "https://spierre91.medium.com/?source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": "Sadrach Pierre, Ph.D."}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fsubscribe%2Fuser%2F120b86134681&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&user=Sadrach+Pierre%2C+Ph.D.&userId=120b86134681&source=post_page-120b86134681----7f639ce9a3d---------------------follow_byline-----------", "anchor_text": "Follow"}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fbookmark%2Fp%2F7f639ce9a3d&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&source=--------------------------bookmark_header-----------", "anchor_text": ""}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fbookmark%2Fp%2F7f639ce9a3d&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&source=--------------------------bookmark_header-----------", "anchor_text": "Save"}, {"url": "https://www.pexels.com/photo/stainless-steel-close-wrench-on-spanner-210881/", "anchor_text": "Source"}, {"url": "https://github.com/spierre91/medium_code/blob/master/basic_python/exception_handling.py", "anchor_text": "GitHub"}, {"url": "https://medium.com/tag/python?source=post_page-----7f639ce9a3d---------------python-----------------", "anchor_text": "Python"}, {"url": "https://medium.com/tag/programming?source=post_page-----7f639ce9a3d---------------programming-----------------", "anchor_text": "Programming"}, {"url": "https://medium.com/tag/data-science?source=post_page-----7f639ce9a3d---------------data_science-----------------", "anchor_text": "Data Science"}, {"url": "https://medium.com/tag/technology?source=post_page-----7f639ce9a3d---------------technology-----------------", "anchor_text": "Technology"}, {"url": "https://medium.com/tag/software-development?source=post_page-----7f639ce9a3d---------------software_development-----------------", "anchor_text": "Software Development"}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fvote%2Ftowards-data-science%2F7f639ce9a3d&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&user=Sadrach+Pierre%2C+Ph.D.&userId=120b86134681&source=-----7f639ce9a3d---------------------clap_footer-----------", "anchor_text": ""}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fvote%2Ftowards-data-science%2F7f639ce9a3d&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&user=Sadrach+Pierre%2C+Ph.D.&userId=120b86134681&source=-----7f639ce9a3d---------------------clap_footer-----------", "anchor_text": ""}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fbookmark%2Fp%2F7f639ce9a3d&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&source=--------------------------bookmark_footer-----------", "anchor_text": ""}, {"url": "https://towardsdatascience.com/?source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": "More from Towards Data Science"}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fsubscribe%2Fcollection%2Ftowards-data-science%2F7f639ce9a3d&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&collection=Towards+Data+Science&collectionId=7f60cf5620c9&source=post_page-----7f639ce9a3d---------------------follow_footer-----------", "anchor_text": "Follow"}, {"url": "https://towardsdatascience.com/?source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": "Read more from Towards Data Science"}, {"url": "https://medium.com/?source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": ""}, {"url": "https://medium.com/about?autoplay=1&source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": "About"}, {"url": "https://help.medium.com/hc/en-us?source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": "Help"}, {"url": "https://policy.medium.com/medium-terms-of-service-9db0094a1e0f?source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": "Terms"}, {"url": "https://policy.medium.com/medium-privacy-policy-f03bf92035c9?source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": "Privacy"}, {"url": "https://itunes.apple.com/app/medium-everyones-stories/id828256236?pt=698524&mt=8&ct=post_page&source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": ""}, {"url": "https://play.google.com/store/apps/details?id=com.medium.reader&source=post_page-----7f639ce9a3d--------------------------------", "anchor_text": ""}, {"url": "https://spierre91.medium.com/?source=---two_column_layout_sidebar----------------------------------", "anchor_text": ""}, {"url": "https://spierre91.medium.com/?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Sadrach Pierre, Ph.D."}, {"url": "https://spierre91.medium.com/followers?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "3.7K Followers"}, {"url": "https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fsubscribe%2Fuser%2F120b86134681&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&user=Sadrach+Pierre%2C+Ph.D.&userId=120b86134681&source=post_page-120b86134681--two_column_layout_sidebar-----------------------follow_profile-----------", "anchor_text": "Follow"}, {"url": "https://medium.com/m/signin?actionUrl=%2F_%2Fapi%2Fsubscriptions%2Fnewsletters%2F4efebd4f21b7&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fexception-handling-in-python-7f639ce9a3d&newsletterV3=120b86134681&newsletterV3Id=4efebd4f21b7&user=Sadrach+Pierre%2C+Ph.D.&userId=120b86134681&source=---two_column_layout_sidebar-----------------------subscribe_user-----------", "anchor_text": ""}, {"url": "https://help.medium.com/hc/en-us?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Help"}, {"url": "https://medium.statuspage.io/?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Status"}, {"url": "https://about.medium.com/creators/?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Writers"}, {"url": "https://blog.medium.com/?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Blog"}, {"url": "https://medium.com/jobs-at-medium/work-at-medium-959d1a85284e?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Careers"}, {"url": "https://policy.medium.com/medium-privacy-policy-f03bf92035c9?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Privacy"}, {"url": "https://policy.medium.com/medium-terms-of-service-9db0094a1e0f?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Terms"}, {"url": "https://medium.com/about?autoplay=1&source=---two_column_layout_sidebar----------------------------------", "anchor_text": "About"}, {"url": "https://speechify.com/medium?source=---two_column_layout_sidebar----------------------------------", "anchor_text": "Text to speech"}]}, "scrape_status": {"code": "1"}}